

const colors = {
  AliceBlue: 'Alice Blue' ,
  AntiqueWhite: 'Antique White' ,
  Aqua: 'Aqua' ,
  Aquamarine: 'Aquamarine' ,
  Azure: 'Azure' ,
  Beige: 'Beige' ,
  Bisque: 'Bisque' ,
  Black: 'Black' ,
  BlanchedAlmond: 'Blanched Almond' ,
  Blue: 'Blue' ,
  BlueViolet: 'Blue Violet' ,
  Brown: 'Brown' ,
  BurlyWood: 'Burly Wood' ,
  CadetBlue: 'Cadet Blue' ,
  Chartreuse: 'Chartreuse' ,
  Chocolate: 'Chocolate' ,
  Coral: 'Coral' ,
  CornflowerBlue: 'Cornflower Blue' ,
  Cornsilk: 'Cornsilk' ,
  Crimson: 'Crimson' ,
  Cyan: 'Cyan' ,
  DarkBlue: 'Dark Blue' ,
  DarkCyan: 'Dark Cyan' ,
  DarkGoldenrod: 'Dark Goldenrod' ,
  DarkGray: 'Dark Gray' ,
  DarkGreen: 'Dark Green' ,
  DarkKhaki: 'Dark Khaki' ,
  DarkMagenta: 'Dark Magenta' ,
  DarkOliveGreen: 'Dark Olive Green' ,
  DarkOrange: 'Dark Orange' ,
  DarkOrchid: 'Dark Orchid' ,
  DarkRed: 'Dark Red' ,
  DarkSalmon: 'Dark Salmon' ,
  DarkSeaGreen: 'Dark Sea Green' ,
  DarkSlateBlue: 'Dark Slate Blue' ,
  DarkSlateGray: 'Dark Slate Gray' ,
  DarkTurquoise: 'Dark Turquoise' ,
  DarkViolet: 'Dark Violet' ,
  DeepPink: 'Deep Pink' ,
  DeepSkyBlue: 'Deep Sky Blue' ,
  DimGray: 'Dim Gray' ,
  DodgerBlue: 'Dodger Blue' ,
  FireBrick: 'Fire Brick' ,
  FloralWhite: 'Floral White' ,
  ForestGreen: 'Forest Green' ,
  Fuchsia: 'Fuchsia' ,
  Gainsboro: 'Gainsboro' ,
  GhostWhite: 'Ghost White' ,
  Gold: 'Gold' ,
  Goldenrod: 'Goldenrod' ,
  Gray: 'Gray' ,
  Green: 'Green' ,
  GreenYellow: 'Green Yellow' ,
  Honeydew: 'Honeydew' ,
  HotPink: 'Hot Pink' ,
  IndianRed: 'Indian Red' ,
  Indigo: 'Indigo' ,
  Ivory: 'Ivory' ,
  Khaki: 'Khaki' ,
  Lavender: 'Lavender' ,
  LavenderBlush: 'Lavender Blush' ,
  LawnGreen: 'Lawn Green' ,
  LemonChiffon: 'Lemon Chiffon' ,
  LightBlue: 'Light Blue' ,
  LightCoral: 'Light Coral' ,
  LightCyan: 'Light Cyan' ,
  LightGoldenrodYellow: 'Light Goldenrod Yellow' ,
  LightGreen: 'Light Green' ,
  LightGrey: 'Light Grey' ,
  LightPink: 'Light Pink' ,
  LightSalmon: 'Light Salmon' ,
  LightSeaGreen: 'Light Sea Green' ,
  LightSkyBlue: 'Light Sky Blue' ,
  LightSlateGray: 'Light Slate Gray' ,
  LightSteelBlue: 'Light Steel Blue' ,
  LightYellow: 'Light Yellow' ,
  Lime: 'Lime' ,
  LimeGreen: 'Lime Green' ,
  Linen: 'Linen' ,
  Magenta: 'Magenta' ,
  Maroon: 'Maroon' ,
  MediumAquamarine: 'Medium Aquamarine' ,
  MediumBlue: 'Medium Blue' ,
  MediumOrchid: 'Medium Orchid' ,
  MediumPurple: 'Medium Purple' ,
  MediumSeaGreen: 'Medium Sea Green' ,
  MediumSlateBlue: 'Medium Slate Blue' ,
  MediumSpringGreen: 'Medium Spring Green' ,
  MediumTurquoise: 'Medium Turquoise' ,
  MediumVioletRed: 'Medium Violet Red' ,
  MidnightBlue: 'Midnight Blue' ,
  MintCream: 'Mint Cream' ,
  MistyRose: 'Misty Rose' ,
  Moccasin: 'Moccasin' ,
  NavajoWhite: 'Navajo White' ,
  Navy: 'Navy' ,
  OldLace: 'Old Lace' ,
  Olive: 'Olive' ,
  OliveDrab: 'Olive Drab' ,
  Orange: 'Orange' ,
  OrangeRed: 'Orange Red' ,
  Orchid: 'Orchid' ,
  PaleGoldenrod: 'Pale Goldenrod' ,
  PaleGreen: 'Pale Green' ,
  PaleTurquoise: 'Pale Turquoise' ,
  PaleVioletRed: 'Pale Violet Red' ,
  PapayaWhip: 'Papaya Whip' ,
  PeachPuff: 'Peach Puff' ,
  Peru: 'Peru' ,
  Pink: 'Pink' ,
  Plum: 'Plum' ,
  PowderBlue: 'Powder Blue' ,
  Purple: 'Purple' ,
  Red: 'Red' ,
  RosyBrown: 'Rosy Brown' ,
  RoyalBlue: 'Royal Blue' ,
  SaddleBrown: 'Saddle Brown' ,
  Salmon: 'Salmon' ,
  SandyBrown: 'Sandy Brown' ,
  SeaGreen: 'Sea Green' ,
  Seashell: 'Seashell' ,
  Sienna: 'Sienna' ,
  Silver: 'Silver' ,
  SkyBlue: 'Sky Blue' ,
  SlateBlue: 'Slate Blue' ,
  SlateGray: 'Slate Gray' ,
  Snow: 'Snow' ,
  SpringGreen: 'Spring Green' ,
  SteelBlue: 'Steel Blue' ,
  Tan: 'Tan' ,
  Teal: 'Teal' ,
  Thistle: 'Thistle' ,
  Tomato: 'Tomato' ,
  Turquoise: 'Turquoise' ,
  Violet: 'Violet' ,
  Wheat: 'Wheat' ,
  White: 'White' ,
  WhiteSmoke: 'White Smoke' ,
  Yellow: 'Yellow' ,
  YellowGreen: 'Yellow Green'
}

export {
  colors
}